### ISSUE TITLE
Automate Elasticsearch 5.x Java Dependency

### ISSUE THREAD

**Issue by rmm5t** [codeship/scripts#173]
The `elasticsearch.sh` script mentions that JDK 8 is necessary for elasticsearch v5, and that steps should be taken to switch to that version of the JDK before launching elasticsearch. However, why not just automatically run `jdk_switcher use oraclejdk8` in the check for ES v5?

```bash
# Make sure to use Oracle JDK 8 for Elasticsearch 5.x run the following commands in your script.
# source $HOME/bin/jdk/jdk_switcher
# jdk_switcher home oraclejdk8
# jdk_switcher use oraclejdk8
if [ ${ELASTICSEARCH_VERSION:0:1} -eq 5 ]
then
  jdk_switcher use oraclejdk8  # <--- Why not automate this?
  ELASTICSEARCH_DL_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz"
elif [ ${ELASTICSEARCH_VERSION:0:1} -eq 2 ]
#...
```

Perhaps the complication is switching back to the original JDK version that was in play after the elasticsearch script is finished?

**Comment by joesiewert** [comment]
Thanks for the feedback @rmm5t. I think the intention is to keep these steps separate so that it is clear in the build steps what Java version is getting set instead of hiding it behind the scenes.

That said, I would absolutely encourage you to copy this script into your repository and make the modifications that would work best for your project.
